require:
  - rubocop-rspec
  - rubocop-faker

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable

Metrics/AbcSize: { Enabled: false }
Metrics/ClassLength: { Max: 200 }
Metrics/MethodLength: { Max: 30 }

Style/Documentation: { Enabled: false }
Style/FrozenStringLiteralComment: { Enabled: false }
Style/HashSyntax:
  EnforcedShorthandSyntax: never
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
  AllowParenthesesInMultilineCall: true
  AllowParenthesesInChaining: true
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%I': '()'
    '%w': '()'
    '%W': '()'

RSpec/BeforeAfterAll: { Enabled: false }
RSpec/DescribeClass: { Enabled: false }
RSpec/ExampleLength: { Enabled: false }
RSpec/InstanceVariable: { Enabled: false }
RSpec/MultipleExpectations: { Enabled: false }
